### ISSUE TITLE
Error search tagged pages

### ISSUE THREAD

**Issue by Nick222** [jaap-karssenberg/zim-desktop-wiki#260]
Xubutu 17.10-64
bzr 2.7.0

Menu Zim: Search - Search tagged pages

Error window:

> This is zim 0.67
> Platform: posix
> Locale: ru_RU UTF-8
> FS encoding: UTF-8
> Python: (2, 7, 14, 'final', 0)
> Gtk: (2, 24, 31)
> Pygtk: (2, 24, 0)
> No bzr version-info found
> 
> ======= Traceback =======
>   File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 157, in do_activate
>     self.__get__(instance, instance.__class__)()
>   File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
>     self.func(instance, *args, **kwargs)
>   File "/home/nick/.local/share/zim/plugins/search_tagged_pages.py", line 132, in search_tagged_pages
>     self.progress_bar_fraction = self.index.n_list_all_pages() / 100000.0
> AttributeError: 'Index' object has no attribute 'n_list_all_pages'

**Comment by muguu** [comment]
@Nick222 Thank you for raising this issue. I started a revision of the code some weeks ago but haven't had time to complete it. If you are interested in using this version, I could do a quick bugfixing to make it work with Zim >= 0.66

**Comment by Nick222** [comment]
In early 2018, if it is possible... :)
Best regards! :)

**Comment by muguu** [comment]
Please give this quick fix a try:
https://gist.github.com/muguu/ebc641fce65fb4cccd63385b96f59e07#file-find_tagged_pages-py

I renamed the plugin to "Find tagged pages" as it is used more for finding tagged pages than searching in tagged pages. You will need to manually delete the old plugin file from the plugins folder.

Cheers!

**Comment by Nick222** [comment]
Very good! Thank You! :)

**Comment by muguu** [comment]
@Nick222 
Perhaps you find the time to test this new version which I put together and let me know what you think.
https://gist.github.com/muguu/4b4b143f87c8e1ae5554c9211279d2e0#file-find_tagged_pages_wip-py

Cheers!

**Comment by Nick222** [comment]
Quick and good! :)

**Comment by muguu** [comment]
Great to hear :) If you find anything weird or could be done better then you know where to find me ;)

**Comment by muguu** [comment]
@Nick222 a little update...
https://gist.github.com/muguu/4b4b143f87c8e1ae5554c9211279d2e0#file-find_tagged_pages_wip-py

**Comment by Nick222** [comment]
Thank You :)

**Comment by jfromero** [comment]
Hi @muguu, 

I am trying the tag autocompletion plugin and it has an issue with Spanish accents (á, é, í, ó, ú - uppercase and lowercase). When I try to write them inside a tag, the plugin replaces them with two characters:

@﹑a

Accent in Zim is showed like a square with four zeroes inside:

![autocomplete tag issue](https://user-images.githubusercontent.com/2708454/42558104-89a43dc6-84f0-11e8-99a9-ff67fad1c31e.png)

Could you take a look please?

Thanks a lot and best regards

**Comment by muguu** [comment]
Hi @jfromero ,

as a workaround: when you start typing a tag with @ and the Tag autocompletion plugin start, please try to ESC the plugin and continue writing the tag.

I'm not sure if such tags are handled properly within zim. I will look into it.

BTW: Which version of the plugin do you use?

Regards,
M.

**Comment by jaap-karssenberg** [comment]
Closing the issue here, as it does not related to a plugin that is currently in the base version of zim. Please create a separate repository for this plugin and track issues there.
